# Site
repository:  Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Bozhidar Gorchev
title: Frontend Developer
email: bojidargo@gmail.com
# email_title: Email (Email title override)
phone: +359 878 208 373




# Dark Mode (true/false/never)
darkmode: false

# Social links

github_username:  static1010
stackoverflow_username: static10
facebook_username: Bojakta
instagram_username: bojidargorchev
linkedin_username: bozhidar-gorchev-70187b203



# Additional icon links
additional_links:
- title: зааааааааааааааааааааааааааааааааааааааааааааааааааааааааааа
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://www.facebook.com/Bojakta/)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://www.facebook.com/Bojakta/)
#   url: Link url (eg. https://www.facebook.com/Bojakta/)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/bg.jpg
about_content:  | # this will include new lines to allow paragraphs 
   Solution-driven professional excelling in highly collaborative work environment, finding solutions
   to challenges and focused on customer satisfaction. My interest and knowledge are in a JavaScript and React.
   Responding to challenges by designing and developing solutions and building web applications aligned to customer's services. Translating
   solutions into code.
     I work on my own project with follow technologies:  
       - RACT 
       - JavaScript
       - CSS
       - HTML5
        
  
    
    You can see my GitHub profile: https://github.com/static1010
    
  
    
content:
   - title: Projects # Title for the section
     layout: list # Type of content section (list/text)
     content:
       - layout: left
         title: Food Order
         link: https://static1010.github.io/Food-Order/
         link_text: 
         additional_links: 
            title:  Food Order
            icon: fab fa-github
            url:  https://static1010.github.io/Food-Order/
     description:   |  # this will include new lines to allow paragra  
               The project is built for the purchase of different types   of food. It is built on React, CSS modules are used   for styling.
         
   - title:  More Projects
     layout: list
     content:
     - layout: left
       title: Calendar for expenses
       link:  https://github.com/static1010/Calendar-for-expenses.git
       description: | # this will include new lines to allow paragraphs
         Тhe project provides information on costs over months and years. It is built on React  
 
   - title: Experience
     layout: list
     content:
     - layout: right
       title: VITOSHA 13
       sub_title: DIRECTOR
       caption: Date Range (August 2017 - March 2020)
       link: http://www.vitosha-academy.com/bg
     
       
       description: | # this will include new lines to allow paragraphs
         Head of a sport Academy with twenty coaches and two hundred children in period of three years.
               
   - title: More Experience
     layout: list
     content:
      - layout: right
        title: AK MANAGEMENT
        sub_title: ADMINISTRATOR and TECHNICAL SUPPORT
        caption: Date Range (March 2014 - August 2017)
        link: http://www.vitosha-academy.com/bg
        quote: > 
           Technical support
        
        description:  |  # this will include new lines to allow paragraphs
          
             Responsible for the entire administration, documentation and organization of the company AK Managment.   
             
             
   - title: Education
     layout: list
     content:
      - layout: top-right
        title: MTM College
        sub_title: MARKETING AND MANAGMENT (Bachelor dregree)
        caption: Date Range ( September 2009 - September 2014)
        quote: >
          Courses description:
        description: | # this will include new lines to allow paragraphss
           - HTML / CSS / JAVASCRIPT --- SOFT ACADEMY / PLURALSIGHT (September 2020 - December 2020) 
           - CSS / JAVASCRIPT --- SOFT ACADEMY / TELERIK / UDEMY (Januray 2021 - February 2021) 
           - JAVASCRIPT --- SOFTUNI / UDEMY (February 2021 - September 2021) 
           - REACT --- SOFTUNI / UDEMY (September 2021 - November 2021) 
           
          
          
          
      
   - title: A Little More About Me
     layout: text
     content: | # this will include new lines to allow paragraphs
      I study programming for more than a year. I went through many courses to learn HTML, CSS, Database, JavaScript, React. 
      I spend all my time studying in the field of programming and I dream of realizing myself in this field.
      I graduated in marketing and management. During my career I worked mainly as a technical assistant and head of a sports academy with two hundred children and twenty teachers.
      I have organized many charity campaigns to help children and their better future.
      A year ago i discovered my new passion in programming and decided to take on this new challenge.
      My hobbies are football, snowboarding, cinema, fitness, cooking, good music.
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
